version: 3,7

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: "no"
    environment:
      DB_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - gptbot

  backend:
    container_name: backend
    depends_on: 
      - mysql
    build:
      context: "./backend"
    restart: "no"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      GPT_API_KEY: ${GPT_API_KEY}
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - ./backend:/opt
    networks:
      - gptbot


volumes:
  mysql:
    driver: local
    
networks:
  gptbot: {}